pallettesDirWin: E:\\Spidergod\\Images\\Color pallettes
pallettesDirLinux: /mr-flopsy/Spidergod/Images/Color Pallettes
hueIP: 10.0.0.11

controllers:
  bedroomRelays:
    name: bedroomRelays
    ip: 10.0.0.13
    system: CustomRelay
    room: bedroom
  bedroomFC:
    name: bedroomFC
    ip: 10.0.0.9
    system: Fadecandy
    room: bedroom
