pallettesDirWin: E:\\Spidergod\\Images\\Color pallettes
pallettesDirLinux: /mr-flopsy/Spidergod/Images/Color Pallettes
hueIP: 192.168.2.47

controllers:
  bedroomRelays:
    name: bedroomRelays
    ip: 192.168.2.45
    system: CustomRelay
    room: bedroom
  bedroomFC:
    name: bedroomFC
    ip: 192.168.2.43
    system: Fadecandy
    room: bedroom
