pallettesDirWin: E:\\Spidergod\\Images\\Color pallettes
pallettesDirLinux: /mr-flopsy/Spidergod/Images/Color Pallettes
hueIP: 192.168.0.12

controllers:
  bedroomRelays:
    name: bedroomRelays
    ip: 192.168.0.19
    system: CustomRelay
    room: bedroom
  bedroomFC:
    name: bedroomFC
    ip: 192.168.0.17
    system: Fadecandy
    room: bedroom
