pallettesDirWin: E:\\Spidergod\\Images\\Color pallettes
pallettesDirLinux: /mr-flopsy/Spidergod/Images/Color Pallettes
hueIP: 10.0.0.20

controllers:
  officeFC:
    name: officeFC
    ip: 10.0.0.100
    system: Fadecandy
    room: office

  bedroomFC:
    name: bedroomFC
    ip: 10.0.0.102
    system: Fadecandy
    room: bedroom

    officeRelays:
      name: officeRelays
      ip: 10.0.0.50
      system: Customrelay
      room: office
