pallettesDirWin: E:\\Spidergod\\Images\\Color pallettes
pallettesDirLinux: /mr-flopsy/Spidergod/Images/Color Pallettes
hueIP: 192.168.0.12

controllers:
  officeFC:
    name: bedroomRelays
    ip: 192.168.0.19
    system: CustomRelay
    room: bedroom
